fprintf('Allocated 2D data:\n')
astra_mex_data2d('info')
fprintf('Allocated 3D data:\n')
astra_mex_data3d('info')
fprintf('Allocated algorithm objects:\n')
astra_mex_algorithm('info')
fprintf('Allocated projectors:\n')
astra_mex_projector('info')
