function LinePlots3(phase,BRO,CTF1,CTF2,x,y)
    
    if nargin<5,x=532;end;
    if nargin<6,y=1:1000;end;

figure, ...
plot(y,CTF1(y,x,1),'green', ... 
     y,CTF2(y,x,1),'magenta', ... 
     y,BRO(y,x,1),'--b', ... 
     y,phase(y,x),'black' ... 
     );
