function [fitresult, gof] = CTFanalysis_FitLine(xn, y, SinePrefactor)
%CREATEFIT(XN,Y)
%  Create a fit.
%
%  Data for 'fit' fit:
%      X Input : xn
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Apr-2015 11:46:39 using cftool

if nargin < 3
    SinePrefactor = 100;
end

%% Fit: 'fit'.
[xData, yData] = prepareCurveData( xn, y );

% Set up fittype and options.
ft = fittype( 'abs( sin( pf * x^2 )) * (a0 + a1*x + a2*x^2 + a3*x^3 + a4*x^4 + a5*x^5)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
%opts.StartPoint = [0.9 0.6 0.1 0.4 0.9 0.8 SinePrefactor];
opts.StartPoint = [-500 1000 -1000 1000 -1000 1000 SinePrefactor];


% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
