function cf_ = FitCritExpoNoPlots(x,y,a,b,cexp,xc)
%CREATEFIT Create plot of data sets and fits
%   CREATEFIT(X,Y)
%   Creates a plot, similar to the plot in the main Curve Fitting Tool,
%   using the data that you provide as input.  You can
%   use this function with the same data you used with CFTOOL
%   or with different data.  You may want to edit the function to
%   customize the code and this help message.
%
%   Number of data sets:  1
%   Number of fits:  1

% Data from data set "y vs. x":
%     X = x:
%     Y = y:
%     Unweighted

% Auto-generated by MATLAB on 20-Jun-2011 11:25:27

if nargin < 3
    a(1) = 0; a(2) = 4; a(3) = 1000;
end
if nargin < 4
    b(1) = 0; b(2) = 140; b(3) = 1000;
end
if nargin < 5
    cexp(1) = 0; cexp(2) = 0.3; cexp(3) = 10;
end
if nargin < 6
    xc(1) = 0; xc(2) = 355; xc(3) = 1000;
end

x = x(:);
y = y(:);


% --- Create fit "fit 1"
fo_ = fitoptions('method','NonlinearLeastSquares','Lower',[a(1) b(1) cexp(1) xc(1)],'Upper',[a(3) b(3) cexp(3) xc(3)]);
ok_ = isfinite(x) & isfinite(y);
if ~all( ok_ )
    warning( 'GenerateMFile:IgnoringNansAndInfs',...
        'Ignoring NaNs and Infs in data.' );
end
st_ = [a(2) b(2) cexp(2) xc(2)];
set(fo_,'Startpoint',st_);
ft_ = fittype('a*abs(x-xc)^cexp+b',...
    'dependent',{'y'},'independent',{'x'},...
    'coefficients',{'a', 'b', 'cexp', 'xc'});

% Fit this model using new data
cf_ = fit(x(ok_),y(ok_),ft_,fo_);
% Alternatively uncomment the following lines to use coefficients from the
% original fit. You can use this choice to plot the original fit against new
% data.
%    cv_ = { 3.8922974284993618888, 139.58845615648766625, 0.35403053618911400902, 355.52946159755117606};
%    cf_ = cfit(ft_,cv_{:});
