function [fitresult, gof] = FitIntLineNoPlots2(x, y1, SinArg)
%CREATEFIT(X,Y1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Jun-2015 08:53:33


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y1 );

% Set up fittype and options.
ft = fittype( 'a*exp(-b2*pf*x^2-b1*sqrt(pf*x^2))*abs(sin(pf*x^2))+c+d*sqrt(pf*x^2)+ee*pf*x^2+f*sqrt(pf*x^2)^3+g*sqrt(pf*x^2)^4+h*sqrt(pf*x^2)^5', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 -10 -10 -10 -10 -10 -10 -10 -10 0];
opts.StartPoint = [0.1 0 0 0 0 0 0 0 0 SinArg];
opts.Upper = [10 10 10 10 10 10 10 10 10 10];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'y1 vs. x', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel x
% ylabel y1
% grid on


